---
# include file for kubernetes - Red Hat based

- name: Add Kubernetes Repository - RPM based
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    state: present
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg,https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#    exclude: kubelet,kubeadm,kubectl    
  when: ansible_facts['os_family'] == "RedHat"

- name: Install K8s
  yum:
    name: kubelet,kubeadm,kubectl
    state: present
  when: ansible_facts['os_family'] == "RedHat"

